global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:9102']

  - job_name: 'docker'
    static_configs:
      - targets: ['ilias:8081']
