entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"
  ipaccess:
    address: ":8081"
  metrics:
    address: ":9102"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@example.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

metrics:
  prometheus:
    entryPoint: metrics

api:
  dashboard: true
